-- load lua caching
pcall(require, 'impatient')

require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.augroups")
require("user.mason")
require("user.lsp")
require("user.treesitter")
require("user.nullls")
require("user.cmp")
require("user.tabnine")
require("user.comment")
require("user.gitsigns")
require("user.aerial")
require("user.telescope")
require("user.nvimtree")
require("user.lualine")
require("user.dressing")
require("user.glow")
require("user.ufo")
require("user.dap")
require("user.rust")
